### ISSUE TITLE
In installed register of Twinpack catalog the download counter does not match the real download counts

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#107]
I just added the ZApplication, then all libraries get installed and this register in catalog gets updated. The first library at the very top (which i installed) shows the right download count, all others show 0

![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/98e9e0bc-6b55-46e8-bda0-afcd6f0c8544)

**Comment by iadonkey** [comment]
what version? should be fixed since https://github.com/Zeugwerk/Twinpack/commit/bf17626dc90b0a9da66553c59c4df21eda153a70 in [0.3.57.0](https://github.com/Zeugwerk/Twinpack/releases/tag/0.3.57.0) and

**Comment by iadonkey** [comment]
Checked and it is fixed since 0.4.x
