### ISSUE TITLE
Display Version Information

### ISSUE THREAD

**Issue by georgtauber-durst** [Zeugwerk/Twinpack#130]
Where can i find, which Version is installed and running in VS?

There is no "about" windows or else.
Also no information in the log. "C:\Users\<USER>\AppData\Local\Zeugwerk\logs\Twinpack"

**Comment by iadonkey** [comment]
The information is currently not shown in visual studio, but you should be able to see it in the properties of the Twinpack.15.dll or Twinpack.17.dll respectively.

Will add the version information in the next release

**Comment by iadonkey** [comment]
Will be available in the next release (> 1.0.7)
