### ISSUE TITLE
library icons are only shown at the first time when opening twinpack catalog

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#44]
when twinpack catalog gets opened the first time (after shell opening a project), it looks right

![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/1cb5a825-7c50-4739-a56c-273a4325ac5d)

When i open the catalog a second time it looks like this (without icons)

![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/e821f26c-0e14-4382-bc64-eddf34f375a0)

**Comment by iadonkey** [comment]
There is some general issue with the BitmapImageSource cache, not sure how this has to be configured to work properly. Accordingly to the documentation it should work as it is
