### ISSUE TITLE
make an icon with a higher resolution to avoid seeing pixels of the icon

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#47]
![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/9004983f-6ec8-4a47-8e06-fdd597c5e887)

**Comment by iadonkey** [comment]
@seehma could you replace the icon if a highres one? I just copied the one from the creator

**Comment by seehma** [comment]
the logo from the video tutorial is highres (800*750) and it is also showing pixels, i think thats another problem when scaling the picture down?
