### ISSUE TITLE
installed entry on a library does not show if a library is installed

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#49]
if one installed a library, closes twinpack catalog and opens it again, installed is empty

![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/78a421d4-9f20-4bc5-bf0c-7111e3f86a58)

or should this show referenced?

Edit:
it seems like creator overwrites the config.json file

Edit:
it looks like that the installed entry does not see that this library version is allready installed in twincat? is it supposed to do so?
![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/f4705cd8-f29c-434c-8d4d-c3957ee54613)

**Comment by iadonkey** [comment]
installed und the catalog should be renamed to „referenced“ to avoid this confusion. The catalog is not supposed to show which package are installed on the system as this information is not PLC specific

**Comment by seehma** [comment]
ok, aber woher weiß der katalog dann welche library ich schon mal "installiert" habe und welche nicht?
muss ich bei jedem projekt die library dann neu runterladen und der katalog läuft komplett unabhängig vom library-repo der twincat installation?

**Comment by iadonkey** [comment]
Twinpack is scanning the twincat library repository to do that.
