### ISSUE TITLE
create an entry with "referenced version" to quickly see which version is referenced in the project

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#50]
i assume, installed shows all installed version of a library, and available a list with all available versions of a library

![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/b6159624-7974-4737-add1-0204e7d5dd8b)

maybe a referenced entry would be nice to quickly see which version is referenced in the project

**Comment by iadonkey** [comment]
the dialog actually shows the referenced library and not installed versions. In a Twincat context it might actually better to rename „installed“ and „install“ to „referenced“ and „add“ though
