### ISSUE TITLE
in publish dialogue one cannot make more than one line in notes field

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#52]
![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/aa0e9eca-2c2a-4e81-98fa-463ac2f5ba48)

after "ein paar kleine notizen", pressing enter does not work to make a new line for more notes

**Comment by iadonkey** [comment]
Notes are limited to 255 characters for now, they should be kept short

**Comment by seehma** [comment]
ok, but a new line is not possible, which would be nice i think
