### ISSUE TITLE
after publishing a first version of a library the version number does not get updated if there is a new one

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#53]
when the first version of a library was published (lets assume 1.0.0.0) and we want to publish a new version (lets assume 1.1.0.0) and we click on publish again -> the version number does not get updated in the publish dialogue.

![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/eda9e14f-09ba-4567-bc69-d1eb492892e3)

iam not sure if it should!?

**Comment by iadonkey** [comment]
The master is the config.json for packages installed with Twinpack
