### ISSUE TITLE
closing twinpack catalogue, publish and modify dialogue window with escape if it is floating should be possible

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#55]
just an idea, should be discussed

if the window is floating maybe it would be nice to close it by pressing esc on the keyboard
![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/aeb7d94e-817a-4633-962a-f2a7129ea609)

the same for **publish** and **modify** windows

**Comment by iadonkey** [comment]
Catalog is a dock, which don't close by pressing escape. Implemented the behavior for the dialogs though
