### ISSUE TITLE
when adding zcore as placeholder, depencies are not shown correctly in publish dialogue

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#56]
if i add a dependency (e.g. ZCore) with a fixed version number it gets showed as follows:
![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/5528caca-11cf-44f6-9e9b-add32a4b8cfa)
![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/6856316c-3f5b-4c6b-b996-f98cf9310705)

When i add it as a placeholder like this
![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/dc329446-97ba-46a7-bca6-d1bdf677fd5e)

No dependencies are shown in publish dialogue
![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/4cedc81e-e80d-4f07-8bbb-d5c33d16bad8)

**Comment by seehma** [comment]
but this is only done when i add a library as placeholder without auto resolution. when i select a version (for the placeholder), die Dependency is shown. Even when i do this outside of the catalogue

**Comment by iadonkey** [comment]
ok, got it, I am not picking up references that are using the DefaultResolution
