### ISSUE TITLE
adding description field to the fields on the right side of the dialogue

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#57]
on the left side is a description shown, this could also be added to the options on the right side of the dialogue

![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/866aa9f8-3390-4144-af26-31aa147b362d)

**Comment by iadonkey** [comment]
why would we show the information twice?

**Comment by seehma** [comment]
i like it when there is all information which was entered for this library shown in one place (even if it is duplicate)
