### ISSUE TITLE
modifying a published library changes the icon 

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#58]
if we want to modify some library preferences but we do not change the library icon. the icon gets changed (in my case to a default icon of zeugwerk)

- so i open a library project with the beckhoff shell
- the right icon is shown on the modify dialogue

![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/9bbb187d-f9f4-4389-8c3a-194d8921b741)

- now change some details, but leave the icon as it was 

![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/5c0bba55-cc35-49f9-8fab-20a1ab4012e8)

- click on modify

![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/e370f4b8-64f8-48eb-8ec4-d55c9d69d998)

- icon changed

**Comment by iadonkey** [comment]
This is a backend issue

**Comment by iadonkey** [comment]
fixed
