### ISSUE TITLE
if i open twinpack catalogue dialogue after it was opened once, the initially selected library information is not refreshed

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#59]
open the catalogue and select a library
then close the catalogue and modify the previously selected library (for example edit the notes)
after that open catalogue again, the previously selected library information should be shown on the right, but with old entries, so it seems like the actual entries are not fetched

**Comment by iadonkey** [comment]
All data is cached so it is faster and atm only the refresh button invalidated the cache. Maybe let’s invalidate it always when the dialog is loaded

**Comment by iadonkey** [comment]
the catalog has the refresh button and the dialog will not poll the package information for performance reasons -> won't fix
