### ISSUE TITLE
eventually add a note here (see picture) if the configuration file should be put under version control or not

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#65]
maybe it would be nice for new users to know if the created config file should be version controlled or not
![grafik](https://github.com/Zeugwerk/Twinpack/assets/7335330/102f8d60-912a-4f19-8ae1-6270f358b992)

**Comment by iadonkey** [comment]
I don’t think it is a good idea to integrate to git just for this. Anybody familiar with git can add the file on their own
