### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by jorlarsen** [Zeugwerk/Twinpack#66]
The UI is not very readable when Visual Studio is in dark mode. Should look into that.

**Comment by iadonkey** [comment]
Thanks for submitting this issue we will look into this. Could you post a screenshot how it looks? Just for future reference

**Comment by jorlarsen** [comment]
![image](https://github.com/Zeugwerk/Twinpack/assets/115713951/ebdfc698-a671-4a92-9893-998b9aeef2fd)

**Comment by iadonkey** [comment]
The fix will be in the next patch release
![image](https://github.com/Zeugwerk/Twinpack/assets/84121166/c348928c-9874-4150-a408-17eb34e56a1d)

**Comment by jorlarsen** [comment]
Great and fast work!
