### ISSUE TITLE
Remind User on Installation if Register Button was not pressed

### ISSUE THREAD

**Issue by seehma** [Zeugwerk/Twinpack#78]
When pressing next without pressing the Register Button first, remind the user that he might have forgotten to Register.

**Comment by iadonkey** [comment]
Only if one filled out an email I guess?

**Comment by iadonkey** [comment]
Let’s just get rid of the register button and register by pressing next if the email is valid?

**Comment by seehma** [comment]
I think we should leave the register button, its a good way to show that there is happening something when pressing register. Without this button its not that clear to a new user...

**Comment by iadonkey** [comment]
won’t do, we want to keep registration optional
