### ISSUE TITLE
icon change libray  pixel size?

### ISSUE THREAD

**Issue by runtimevic** [Zeugwerk/Twinpack#88]
Hello @seehma , @iadonkey , @zeugwerker :

The library display icon does not load, what should the icon be like so that it can be chosen?

Thanks you, Víctor.

**Comment by iadonkey** [comment]
it should be a square png image (i.e. 256x256), if no icon is chose one is generated automatically with a hash.
Could you post the image that you tried so we can debug the issue?

**Comment by runtimevic** [comment]
My image does not have the appropriate pixel resolution, I'm going to change it and try it.
thanks...

**Comment by runtimevic** [comment]
Hi, 
I have changed the resolution of the icon and it still does not load..., when choosing it should it be displayed?
![TcMotion_Logo_256x256](https://github.com/Zeugwerk/Twinpack/assets/53791834/34b2d636-0192-486c-b6f2-939fe47ee055)

**Comment by iadonkey** [comment]
Please move the icon into the same folder as the solution and try again, you don't have to publish a new version for this, you can also use "Modify Package" for this (Twinpack Package -> Modify ...)

It was previously a prerequite to have the icon in the same folder. This was later changed, but there seems to be a bug that it doesn't work as intended if the file is on a different drive than the solution

**Comment by iadonkey** [comment]
@runtimevic did you try with moving the file to the folder of the solution? Alternatively, if you update to the latest version (0.2.15) it should work from any location.

**Comment by runtimevic** [comment]
I have to try it...
